export type StockRef = {
  symbol: string
  amount: number
}

export type Stock = {
  ask: number
  askSize: number
  averageDailyVolume10Day: number
  averageDailyVolume3Month: number
  beta: number
  bid: number
  bidSize: number
  bookValue: number
  currency: string
  dividendsPerShare: number
  ebitda: number
  epsForward: number
  epsTrailingTwelveMonths: number
  esgPopulated: boolean
  exchange: string
  exchangeDataDelayedBy: number
  exchangeTimezoneName: string
  exchangeTimezoneShortName: string
  fiftyDayAverage: number
  fiftyDayAverageChange: number
  fiftyDayAverageChangePercent: number
  fiftyTwoWeekHigh: number
  fiftyTwoWeekHighChange: number
  fiftyTwoWeekHighChangePercent: number
  fiftyTwoWeekLow: number
  fiftyTwoWeekLowChange: number
  fiftyTwoWeekLowChangePercent: number
  fiftyTwoWeekRange: number
  firstTradeDateMilliseconds: number
  floatShares: number
  forwardPE: number
  fullExchangeName: string
  gmtOffSetMilliseconds: number
  heldPercentInsiders: number
  heldPercentInstitutions: number
  language: string
  longName: string
  market: string
  marketCap: number
  marketState: string
  messageBoardId: string
  priceHint: number
  priceToBook: number
  priceToSales: number
  quoteSourceName: string
  quoteSummary: any
  quoteType: string
  region: string
  regularMarketChange: number
  regularMarketChangePercent: number
  regularMarketDayHigh: number
  regularMarketDayLow: number
  regularMarketDayRange: string
  regularMarketOpen: number
  regularMarketPreviousClose: number
  regularMarketPrice: number
  regularMarketTime: number
  regularMarketVolume: number
  revenue: number
  sharesOutstanding: number
  shortName: string
  sourceInterval: number
  symbol: string
  totalCash: number
  tradeable: boolean
  trailingPE: number
  triggerable: boolean
  twoHundredDayAverage: number
  twoHundredDayAverageChange: number
  twoHundredDayAverageChangePercent: number
}
